In [1]:
import pandas as pd
import numpy as np
from datetime import date,timedelta

In [2]:
from yahoofinance import HistoricalPrices as get_history
#ensure yahoofinance package is installed  "pip install yahoofinance"
import yfinance as yf

# Change the dates here carefully

In [3]:
start_date = date(2020,12,30)
#date in Year, Month, Day
end_date = date(2021,1,2)

In [4]:
#nifty_50_stocks_list=pd.read_csv('ind_nifty50list2022.csv')
#use the csv file from nifty website
nifty_50_stocks = ["ASIANPAINT","BAJFINANCE","BAJAJFINSV","BRITANNIA",'DIVISLAB','GRASIM','HCLTECH','HDFCBANK',
                   'HINDALCO','HINDUNILVR','ICICIBANK','INFY','JSWSTEEL','LT','NESTLEIND','POWERGRID','RELIANCE','TCS','TATACONSUM','TATASTEEL',
                   'TECHM','TITAN','ULTRACEMCO','WIPRO'] 
#Choose the stock symbols

## Data collection
###

In [5]:
k=0 
for i in nifty_50_stocks :
    print(str(k+1)+": stock_name:\t", i)
    k+=1
    x = yf.download( i+'.NS',start=start_date,end=end_date) #yahoofinance function to get the stock data
    
    x.to_csv('{}.csv'.format(i))

1: stock_name:	 ASIANPAINT
[*********************100%***********************]  1 of 1 completed
2: stock_name:	 BAJFINANCE
[*********************100%***********************]  1 of 1 completed
3: stock_name:	 BAJAJFINSV
[*********************100%***********************]  1 of 1 completed
4: stock_name:	 BRITANNIA
[*********************100%***********************]  1 of 1 completed
5: stock_name:	 DIVISLAB
[*********************100%***********************]  1 of 1 completed
6: stock_name:	 GRASIM
[*********************100%***********************]  1 of 1 completed
7: stock_name:	 HCLTECH
[*********************100%***********************]  1 of 1 completed
8: stock_name:	 HDFCBANK
[*********************100%***********************]  1 of 1 completed
9: stock_name:	 HINDALCO
[*********************100%***********************]  1 of 1 completed
10: stock_name:	 HINDUNILVR
[*********************100%***********************]  1 of 1 completed
11: stock_name:	 ICICIBANK
[*********************100%***********************]  1 of 1 completed
12: stock_name:	 INFY
[*********************100%***********************]  1 of 1 completed
13: stock_name:	 JSWSTEEL
[*********************100%***********************]  1 of 1 completed
14: stock_name:	 LT
[*********************100%***********************]  1 of 1 completed
15: stock_name:	 NESTLEIND
[*********************100%***********************]  1 of 1 completed
16: stock_name:	 POWERGRID
[*********************100%***********************]  1 of 1 completed
17: stock_name:	 RELIANCE
[*********************100%***********************]  1 of 1 completed
18: stock_name:	 TCS
[*********************100%***********************]  1 of 1 completed
19: stock_name:	 TATACONSUM
[*********************100%***********************]  1 of 1 completed
20: stock_name:	 TATASTEEL
[*********************100%***********************]  1 of 1 completed
21: stock_name:	 TECHM
[*********************100%***********************]  1 of 1 completed
22: stock_name:	 TITAN
[*********************100%***********************]  1 of 1 completed
23: stock_name:	 ULTRACEMCO
[*********************100%***********************]  1 of 1 completed
24: stock_name:	 WIPRO
[*********************100%***********************]  1 of 1 completed

In [6]:
nifty50=pd.DataFrame()
nifty50

Empty DataFrame
Columns: []
Index: []

In [7]:
for i in nifty_50_stocks:
    x = pd.read_csv('{}.csv'.format(i), usecols=["Adj Close","Date"],index_col="Date")
    print(x)
    nifty50 = pd.concat([nifty50,x],axis = 1)
                                                       #getting each stock data one by one and concatanating it into the 'allData' frame

              Adj Close
Date
2020-12-30  2717.720947
2020-12-31  2747.637451
2021-01-01  2758.620117
              Adj Close
Date
2020-12-30  5325.544434
2020-12-31  5286.657715
2021-01-01  5271.631836
              Adj Close
Date
2020-12-30  8959.527344
2020-12-31  8904.190430
2021-01-01  8868.299805
              Adj Close
Date
2020-12-30  3512.515381
2020-12-31  3505.115967
2021-01-01  3496.736084
              Adj Close
Date
2020-12-30  3784.187744
2020-12-31  3826.215332
2021-01-01  3833.336182
             Adj Close
Date
2020-12-30  931.912231
2020-12-31  925.379639
2021-01-01  930.914917
             Adj Close
Date
2020-12-30  906.141357
2020-12-31  911.391113
2021-01-01  915.581299
              Adj Close
Date
2020-12-30  1426.326904
2020-12-31  1430.110474
2021-01-01  1418.909058
             Adj Close
Date
2020-12-30  235.768936
2020-12-31  238.897308
2021-01-01  236.712418
              Adj Close
Date
2020-12-30  2374.718506
2020-12-31  2363.666748
2021-01-01  2355.920898
             Adj Close
Date
2020-12-30  527.206299
2020-12-31  533.487915
2021-01-01  525.959961
              Adj Close
Date
2020-12-30  1222.653931
2020-12-31  1231.479614
2021-01-01  1236.039429
             Adj Close
Date
2020-12-30  378.667175
2020-12-31  379.746033
2021-01-01  382.197906
              Adj Close
Date
2020-12-30  1277.589111
2020-12-31  1273.188843
2021-01-01  1282.483643
               Adj Close
Date
2020-12-30  18172.257812
2020-12-31  18183.132812
2021-01-01  18242.902344
             Adj Close
Date
2020-12-30  131.965439
2020-12-31  131.722595
2021-01-01  131.479752
              Adj Close
Date
2020-12-30  1989.101196
2020-12-31  1978.933960
2021-01-01  1981.126831
              Adj Close
Date
2020-12-30  2872.777344
2020-12-31  2826.811523
2021-01-01  2891.489258
             Adj Close
Date
2020-12-30  590.925171
2020-12-31  586.500854
2021-01-01  598.033997
             Adj Close
Date
2020-12-30  626.431458
2020-12-31  629.561462
2021-01-01  629.023438
             Adj Close
Date
2020-12-30  948.103149
2020-12-31  938.412354
2021-01-01  942.992615
              Adj Close
Date
2020-12-30  1548.884277
2020-12-31  1563.399536
2021-01-01  1554.869995
              Adj Close
Date
2020-12-30  5328.746582
2020-12-31  5262.469727
2021-01-01  5265.106934
             Adj Close
Date
2020-12-30  382.914276
2020-12-31  384.757141
2021-01-01  386.600006

In [8]:
nifty50.columns=nifty_50_stocks

In [9]:
nifty50

,ASIANPAINT,BAJFINANCE,BAJAJFINSV,BRITANNIA,DIVISLAB,GRASIM,HCLTECH,HDFCBANK,HINDALCO,HINDUNILVR,...,NESTLEIND,POWERGRID,RELIANCE,TCS,TATACONSUM,TATASTEEL,TECHM,TITAN,ULTRACEMCO,WIPRO
Date,,,,,,,,,,,,,,,,,,,,,
2020-12-30,2717.720947,5325.544434,8959.527344,3512.515381,3784.187744,931.912231,906.141357,1426.326904,235.768936,2374.718506,...,18172.257812,131.965439,1989.101196,2872.777344,590.925171,626.431458,948.103149,1548.884277,5328.746582,382.914276
2020-12-31,2747.637451,5286.657715,8904.190430,3505.115967,3826.215332,925.379639,911.391113,1430.110474,238.897308,2363.666748,...,18183.132812,131.722595,1978.933960,2826.811523,586.500854,629.561462,938.412354,1563.399536,5262.469727,384.757141
2021-01-01,2758.620117,5271.631836,8868.299805,3496.736084,3833.336182,930.914917,915.581299,1418.909058,236.712418,2355.920898,...,18242.902344,131.479752,1981.126831,2891.489258,598.033997,629.023438,942.992615,1554.869995,5265.106934,386.600006

In [10]:
nifty50.to_csv(str(end_date - timedelta(days=1))+'.csv')  #saving the data without preprocessing