# PSO weights(sharpe)
2.3191734495951,16.6295828453036,2.84409459363485,12.9458755262145,17.1340642247542,2.8847206102651,0.000534244624664977,0.472170247696868,0.074847059834868,2.94793693414302,0.0262220023680919,0.346519911265239,3.53047455203853,0.0466825288144165,1.33024971549439,0.0748516834622377,15.5043598396495,4.96252155882404,0.0150397328355891,0.00268458200524248,1.78596797156952,13.993022456867,0.015381069897849,0.113022658841609

# PSO weights(Sortino)
0.740972913431147,5.05530134351254,10.3303401669197,8.13231211400601,0.0947496790349625,0.912113724317866,1.09525615854694,2.93768714239225,0.00561098823877464,0.188076587994896,1.45690682648415,0.0281916748129561,0.36581346738925,0.338467099468225,47.6443547474887,0.127249897550439,0.000609521614862787,0.0165558947681568,0.0464725620727,3.81027487655325,0.149403229823946,15.9669476788883,0.119916590511603,0.436415114178368

In [27]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [28]:
df=pd.read_csv('Filtered_n50.csv',parse_dates=['Date'],index_col='Date')
df = df.loc["2021-01-01" : "2021-12-31"]   #Since 2016-01-01, 5y(1238rows till 2020-12-31), + year 2021's rows
tdf=df.copy()                  #deep copy
df.reset_index(drop=True, inplace=True)

In [29]:
df

,ASIANPAINT,BAJFINANCE,BAJAJFINSV,BRITANNIA,DIVISLAB,GRASIM,HCLTECH,HDFCBANK,HINDALCO,HINDUNILVR,...,NESTLEIND,POWERGRID,RELIANCE,TCS,TATACONSUM,TATASTEEL,TECHM,TITAN,ULTRACEMCO,WIPRO
0,2758.620117,5271.631836,8868.299805,3496.736084,3833.336182,930.914917,923.280396,1418.909058,236.712418,2355.920898,...,18242.900391,135.132904,1981.126831,2891.489258,598.033997,629.023438,942.992554,1554.869995,5265.106934,387.229431
1,2736.903320,5207.785156,8896.592773,3482.132812,3846.482422,961.882263,952.324219,1409.897949,252.552826,2394.354492,...,18170.970703,134.384140,1984.466064,3001.293213,600.519592,677.831238,966.134644,1547.188477,5301.330566,395.510803
2,2776.808350,5110.741699,8818.710938,3480.368896,3826.414795,958.740601,962.960571,1420.551758,248.580322,2418.086182,...,18349.240234,134.063232,1959.795410,3054.170898,606.037598,665.653748,967.966675,1567.190430,5315.262207,405.388580
3,2788.238281,5022.184570,8784.219727,3469.195801,3864.010498,981.978577,950.187134,1414.428345,257.270172,2385.276611,...,18306.724609,139.875015,1908.111694,3013.191895,601.464111,668.832581,961.506287,1568.836426,5421.892090,405.488373
4,2775.218262,5072.803223,8985.821289,3482.034912,3787.524170,991.203918,934.985291,1410.146851,271.025024,2337.468506,...,17923.144531,140.516815,1905.021729,2994.726562,597.387695,706.978943,959.192017,1538.658813,5371.736816,405.837585
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
243,3272.399902,6890.750000,16013.099609,3513.199951,4473.200195,1602.550049,1267.199951,1450.800049,452.799988,2301.399902,...,19302.349609,206.100006,2370.250000,3689.616699,718.500000,1121.800049,1785.000000,2331.300049,7245.049805,699.599976
244,3368.199951,6906.649902,16100.849609,3550.649902,4525.350098,1621.949951,1283.900024,1460.800049,458.149994,2309.100098,...,19355.000000,205.600006,2398.399902,3700.048340,726.950012,1127.449951,1806.099976,2379.850098,7406.100098,705.450012
245,3367.449951,6911.649902,16249.049805,3559.600098,4621.600098,1604.650024,1291.900024,1453.849976,454.250000,2306.850098,...,19399.650391,204.600006,2402.500000,3688.218994,726.650024,1116.250000,1786.849976,2402.149902,7420.950195,703.700012
246,3365.699951,6871.100098,16167.549805,3573.899902,4627.899902,1593.650024,1317.050049,1461.500000,449.649994,2325.600098,...,19406.550781,205.350006,2359.100098,3727.200684,728.000000,1101.000000,1799.949951,2437.300049,7397.200195,714.099976
247,3382.949951,6977.299805,16406.199219,3606.000000,4678.200195,1622.250000,1319.099976,1479.400024,475.549988,2360.149902,...,19705.699219,204.399994,2368.149902,3731.792725,743.450012,1111.449951,1790.550049,2522.399902,7591.049805,715.349976

In [30]:
def number_of_years(y):        #calculates the number of years of the dataset
  p=y.index[0]                 #date of first row in the dataset (datetime format)
  q=y.index[len(y)-1]          #date of last row in the dataset  (datetime format)
  return ((q-p).days+1)/365           #the difference give the number of total days (not trading days) over the total number of years in the dataset

In [31]:
trading_days=len(df)/number_of_years(tdf)                       #Trading days per year (automated)

In [32]:
returnsh=df.pct_change()                  #Here, returnsh would mean return considered for sharpe ratio
returnsh.fillna(0,inplace=True)           #calculating daily returns of the stocks in the portfolio

In [33]:
returnso=returnsh.copy()                  #this cell considers only NEGATIVE returns so as to calculate sortino ratio
for cols in returnso.columns.tolist():
    for i in range(0,len(df)):
      if returnso[cols][i] > 0:
        returnso[cols][i]=0               #Here, returnso would mean return considered for sortino ratio

In [34]:
covmatsh=returnsh.cov()*trading_days      #Annualised covariance matrix calculated wrt returnsh i.e. used to calculate sharpe ratio
covmatso=returnso.cov()*trading_days      #Annualised covariance matrix calculated wrt returnso i.e. used to calculate sortino ratio

In [35]:
num_portfolios = 1                   #initializing number of portfolios to 50000; referred from Wang et al (2020) (science direct)
num_assets = len(df.columns)              #initializing number of stocks/assets considered in the portfolio
risk_free_rate = 0.0358                   #initializing risk free rate that will be used in calculating both the ratios (absolute value)
#referred from url: https://www.rbi.org.in/Scripts/BS_NSDPDisplay.aspx?param=4&Id=24292
#In the above url, the 364 (1 year) day treasury bill is 3.58% , when taken absolute value => 0.0358
# (improved)

In [36]:
#2021_chen etal_Mean–variance portfolio optimization using machine learning-based stock price prediction
#Repeat the process 50,000times. From a statistical point of view, 50,000 random portfolios cover most possible portfolios with different weights and aresufficiently representative

In [37]:
portfolio_returns = []                    #initializing an empty list for portfolio returns
portfolio_volatility =[]                  #initializing an empty list for portfolio risk
stock_weights =[]                         #initializing an empty list for portfolio weights
semi_deviation =[]                        #initializing an empty list for portfolio semi-deviation
sharpe =[]                                #initializing an empty list for portfolio sharpe ratio
sortino =[]                               #initializing an empty list for portfolio sortino ratio

In [38]:
def ratio(a,b,c):                         #function to calculate ratio i.e. "(returns-(risk_free_rate))/deviation"
  return (a-c)/b                          #a => annual return, c => risk_free_rate, b => deviation (standard for sharpe, semi for sortino)

In [39]:
             #iterating forloop for 50000 times to generate 50000 portfolios
weights = [0.740972913431147,5.05530134351254,10.3303401669197,8.13231211400601,0.0947496790349625,
           0.912113724317866,1.09525615854694,2.93768714239225,0.00561098823877464,0.188076587994896,
           1.45690682648415,0.0281916748129561,0.36581346738925,0.338467099468225,47.6443547474887,
           0.127249897550439,0.000609521614862787,0.0165558947681568,0.0464725620727,
           3.81027487655325,0.149403229823946,15.9669476788883,0.119916590511603,0.436415114178368]                       #initializing random weights
weights /= np.sum(weights)                                    #No Short Selling Allowed => weights add up to 1   "x = x+y" => "x+=y"    weights = weights/np.sum(weights)  
returns_temp = np.sum(returnsh.mean()*weights)*trading_days   #calculating annulaised portfolio return
varsh=np.dot(weights.T,np.dot(covmatsh,weights))              #calculating portfolio varience wrt calculating sharpe ratio
varso=np.dot(weights.T,np.dot(covmatso,weights))              #calculating portfolio varience wrt calculating sortino ratio
volatility_temp = np.sqrt(varsh)                              #portfolio risk
semi_temp = np.sqrt(varso)                                    #portfolio semi-deviation
shtemp = ratio(returns_temp,volatility_temp,risk_free_rate)   #calculating sharpe ratio
sotemp = ratio(returns_temp,semi_temp,risk_free_rate)         #calculating sortino ratio
portfolio_returns.append(returns_temp)                       
portfolio_volatility.append(volatility_temp)
stock_weights.append(weights)
sharpe.append(shtemp)
sortino.append(sotemp)
semi_deviation.append(semi_temp)

In [40]:
portfolio = {'Returns' : portfolio_returns, 'Standard Deviation' : portfolio_volatility, 'Semi-Deviation' : semi_deviation, 'Sharpe Ratio' : sharpe, 
             'Sortino Ratio' : sortino}    
#here, 'portfolio' is a dictionary which will be used to create dataframe where each row will be a portfolio

In [41]:
for counter,symbol in enumerate(df.columns):
  portfolio[symbol + " Weight"] = [Weight[counter] for Weight in stock_weights] 
#to the dictionary (named 'portfolio'), weights for each symbol are added in so as to be displayed in the dataframe

In [42]:
pc = pd.DataFrame(portfolio)         #making the final dataframe where data of 50000 portfolios is appended (subject to be saved, whose code is to be written)

In [43]:
pc=pc*100                                       #Converting everything to percentage
pc['Sharpe Ratio']=pc['Sharpe Ratio']/100       #leaving ratios as it is
pc['Sortino Ratio']=pc['Sortino Ratio']/100

In [44]:
pc

,Returns,Standard Deviation,Semi-Deviation,Sharpe Ratio,Sortino Ratio,ASIANPAINT Weight,BAJFINANCE Weight,BAJAJFINSV Weight,BRITANNIA Weight,DIVISLAB Weight,...,NESTLEIND Weight,POWERGRID Weight,RELIANCE Weight,TCS Weight,TATACONSUM Weight,TATASTEEL Weight,TECHM Weight,TITAN Weight,ULTRACEMCO Weight,WIPRO Weight
0,27.127171,15.086652,7.98243,1.560795,2.949875,0.740973,5.055301,10.33034,8.132312,0.09475,...,47.644355,0.12725,0.00061,0.016556,0.046473,3.810275,0.149403,15.966948,0.119917,0.436415

In [45]:
pc.to_csv("PSO_sortino.csv")

In [46]:
pc1=pc.copy()

In [21]:
pc_sharpe=pc.drop(columns=['Sortino Ratio','Semi-Deviation'])

In [22]:
pc_sharpe

,Returns,Standard Deviation,Sharpe Ratio,ASIANPAINT Weight,BAJFINANCE Weight,BAJAJFINSV Weight,BRITANNIA Weight,DIVISLAB Weight,GRASIM Weight,HCLTECH Weight,...,NESTLEIND Weight,POWERGRID Weight,RELIANCE Weight,TCS Weight,TATACONSUM Weight,TATASTEEL Weight,TECHM Weight,TITAN Weight,ULTRACEMCO Weight,WIPRO Weight
0,30.205016,15.527774,1.714671,2.319173,16.629583,2.844095,12.945876,17.134064,2.884721,0.000534,...,1.33025,0.074852,15.50436,4.962522,0.01504,0.002685,1.785968,13.993022,0.015381,0.113023

In [23]:
pc_sharpe.to_csv("Filtered_PSO_Sharpe_2021_summary.csv")

In [47]:
pc_sortino=pc1.drop(columns=['Sharpe Ratio','Standard Deviation'])

In [48]:
pc_sortino

,Returns,Semi-Deviation,Sortino Ratio,ASIANPAINT Weight,BAJFINANCE Weight,BAJAJFINSV Weight,BRITANNIA Weight,DIVISLAB Weight,GRASIM Weight,HCLTECH Weight,...,NESTLEIND Weight,POWERGRID Weight,RELIANCE Weight,TCS Weight,TATACONSUM Weight,TATASTEEL Weight,TECHM Weight,TITAN Weight,ULTRACEMCO Weight,WIPRO Weight
0,27.127171,7.98243,2.949875,0.740973,5.055301,10.33034,8.132312,0.09475,0.912114,1.095256,...,47.644355,0.12725,0.00061,0.016556,0.046473,3.810275,0.149403,15.966948,0.119917,0.436415

In [49]:
pc_sortino.to_csv('Filtered_PSO_Sortino_2021_summary.csv')

                           0
Returns            13.339271
Semi-Deviation     12.072388
Sortino Ratio       0.808396
Adj Close Weight  100.000000