In [3]:
import pandas as pd
import numpy as np
from datetime import date

In [4]:
from yahoofinance import HistoricalPrices as get_history #ensure yahoofinance package is installed  "pip install yahoofinance"

# Code for Data Collection
*Please execute this in jupyter notebook to get the data quickly*

In [30]:
start_date = date(2016,1,1) #date in Year, Month, Day
end_date = date(2021,5,1)

In [31]:
nifty_50_stocks_list=pd.read_csv('ind_nifty50list.csv') #use the csv file from nifty website
nifty_50_stocks = list(nifty_50_stocks_list['Symbol']) #Choose the stock symbols

In [32]:
k=0
for i in nifty_50_stocks :
    print(str(k+1)+"getting: ", i)
    k+=1
    x = get_history(instrument= i+'.NS',start_date=start_date,end_date=end_date) #yahoofinance function to get the stock data
    x.to_csv('nifty50_stocks/{}.csv'.format(i))

1getting:  ADANIPORTS
2getting:  ASIANPAINT
3getting:  AXISBANK
4getting:  BAJAJ-AUTO
5getting:  BAJFINANCE
6getting:  BAJAJFINSV
7getting:  BPCL
8getting:  BHARTIARTL
9getting:  BRITANNIA
10getting:  CIPLA
11getting:  COALINDIA
12getting:  DIVISLAB
13getting:  DRREDDY
14getting:  EICHERMOT
15getting:  GAIL
16getting:  GRASIM
17getting:  HCLTECH
18getting:  HDFCBANK
19getting:  HDFCLIFE
20getting:  HEROMOTOCO
21getting:  HINDALCO
22getting:  HINDUNILVR
23getting:  HDFC
24getting:  ICICIBANK
25getting:  ITC
26getting:  IOC
27getting:  INDUSINDBK
28getting:  INFY
29getting:  JSWSTEEL
30getting:  KOTAKBANK
31getting:  LT
32getting:  M&M
33getting:  MARUTI
34getting:  NTPC
35getting:  NESTLEIND
36getting:  ONGC
37getting:  POWERGRID
38getting:  RELIANCE
39getting:  SBILIFE
40getting:  SHREECEM
41getting:  SBIN
42getting:  SUNPHARMA
43getting:  TCS
44getting:  TATAMOTORS
45getting:  TATASTEEL
46getting:  TECHM
47getting:  TITAN
48getting:  UPL
49getting:  ULTRACEMCO
50getting:  WIPRO

# Code for preprocessing the data

In [34]:
nifty_50_stocks_list=pd.read_csv('ind_nifty50list.csv') #use the csv file from nifty website
nifty_50_stocks = list(nifty_50_stocks_list['Symbol']) #Choose the stock symbols

In [35]:
allData = pd.DataFrame()                               #creating an empty dataframe

In [36]:
 for i in nifty_50_stocks:
   x = pd.read_csv('nifty50_stocks/{}.csv'.format(i), usecols=["Adj Close"])
   allData = pd.concat([allData,x],axis = 1)
                                                       #getting each stock data one by one and concatanating it into the 'allData' frame

In [37]:
allData.columns=nifty_50_stocks                        #setting up the column names of the dataframe

In [38]:
allData.to_csv('raw_data.csv')  #saving the data without preprocessing

In [39]:
allData

,ADANIPORTS,ASIANPAINT,AXISBANK,BAJAJ-AUTO,BAJFINANCE,BAJAJFINSV,BPCL,BHARTIARTL,BRITANNIA,CIPLA,...,SBIN,SUNPHARMA,TCS,TATAMOTORS,TATASTEEL,TECHM,TITAN,UPL,ULTRACEMCO,WIPRO
0,261.112030,850.608887,440.847687,2209.871338,602.348328,1978.543457,217.338654,302.993469,1374.428223,642.229675,...,222.831543,787.287170,1082.013306,401.737305,219.908173,461.389832,340.842285,279.519226,2785.781250,202.975677
1,251.743073,852.593201,429.579071,2179.461182,598.059875,1954.307739,216.222977,290.802551,1368.077148,632.723877,...,215.886398,771.407227,1061.057739,376.897339,219.481003,458.151581,340.212952,275.393219,2711.943848,203.431641
2,249.547195,871.807617,427.668335,2196.136230,592.664673,1940.843384,218.939453,287.821564,1365.361816,628.019958,...,213.000748,772.758789,1051.810791,374.298431,234.346603,463.031219,336.630768,276.313599,2696.061768,203.139801
3,245.741058,858.013977,422.034027,2181.347900,603.474854,1933.413330,221.280106,286.709259,1381.469727,639.044739,...,212.120361,764.505066,1066.431152,365.751862,229.604980,465.870178,336.776001,281.423492,2698.281494,202.483200
4,239.104660,844.413879,401.015594,2123.205322,603.380981,1921.943726,214.476547,286.842743,1356.088257,624.688110,...,204.979584,756.637512,1061.796509,343.410919,213.500595,453.183197,333.096954,264.951294,2631.596191,200.568176
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1309,730.750000,2557.899902,700.450012,3738.850098,4736.549805,10001.750000,418.899994,527.549988,3526.107910,905.400024,...,344.299988,634.700012,3085.706299,295.399994,940.750000,962.200012,1479.849976,590.650024,6275.899902,480.299988
1310,749.150024,2574.350098,699.549988,3785.500000,4865.049805,10091.349609,420.350006,534.299988,3528.100342,912.400024,...,353.049988,639.250000,3116.754150,301.500000,977.750000,969.250000,1495.099976,597.450012,6326.799805,485.049988
1311,746.250000,2614.550049,708.150024,3889.750000,5280.899902,10489.299805,417.500000,544.299988,3465.881348,910.200012,...,363.399994,643.400024,3108.892822,305.899994,971.400024,977.400024,1508.849976,608.049988,6360.799805,489.299988
1312,746.750000,2613.449951,719.400024,3836.449951,5484.850098,11176.549805,419.549988,540.849976,3456.067871,906.500000,...,359.399994,644.500000,3100.085693,301.899994,1031.349976,976.900024,1506.800049,615.799988,6382.450195,489.850006
1313,730.049988,2536.399902,714.900024,3833.750000,5451.899902,11041.650391,421.799988,536.750000,3436.241455,910.349976,...,353.500000,654.450012,3020.873291,293.850006,1034.000000,960.400024,1491.650024,606.900024,6278.950195,492.750000

In [40]:
allData.isnull().sum()               #getting the number of null values in each column as a list

ADANIPORTS      2
ASIANPAINT      2
AXISBANK        2
BAJAJ-AUTO      2
BAJFINANCE      2
BAJAJFINSV      2
BPCL            2
BHARTIARTL      2
BRITANNIA       2
CIPLA           2
COALINDIA       2
DIVISLAB        2
DRREDDY         2
EICHERMOT       2
GAIL            2
GRASIM          2
HCLTECH         2
HDFCBANK        2
HDFCLIFE      466
HEROMOTOCO      2
HINDALCO        2
HINDUNILVR      2
HDFC            2
ICICIBANK       2
ITC             2
IOC             2
INDUSINDBK      2
INFY            2
JSWSTEEL        2
KOTAKBANK       2
LT              2
M&M             2
MARUTI          2
NTPC            2
NESTLEIND       2
ONGC            2
POWERGRID       2
RELIANCE        2
SBILIFE       434
SHREECEM        2
SBIN            2
SUNPHARMA       2
TCS             2
TATAMOTORS      2
TATASTEEL       2
TECHM           2
TITAN           2
UPL             2
ULTRACEMCO      2
WIPRO           2
dtype: int64

In [41]:
                                                            #filling the null values with forward fill and backward fill methods
for i in allData.columns.to_list():
    if allData[i].isnull().sum()>2:
        allData.drop(i,axis=1,inplace=True)
    else:
        allData[i].fillna(method='bfill',axis=0,inplace=True)
        allData[i].fillna(method='ffill',axis=0,inplace=True)               #(important)

In [42]:
allData.isnull().sum()

ADANIPORTS    0
ASIANPAINT    0
AXISBANK      0
BAJAJ-AUTO    0
BAJFINANCE    0
BAJAJFINSV    0
BPCL          0
BHARTIARTL    0
BRITANNIA     0
CIPLA         0
COALINDIA     0
DIVISLAB      0
DRREDDY       0
EICHERMOT     0
GAIL          0
GRASIM        0
HCLTECH       0
HDFCBANK      0
HEROMOTOCO    0
HINDALCO      0
HINDUNILVR    0
HDFC          0
ICICIBANK     0
ITC           0
IOC           0
INDUSINDBK    0
INFY          0
JSWSTEEL      0
KOTAKBANK     0
LT            0
M&M           0
MARUTI        0
NTPC          0
NESTLEIND     0
ONGC          0
POWERGRID     0
RELIANCE      0
SHREECEM      0
SBIN          0
SUNPHARMA     0
TCS           0
TATAMOTORS    0
TATASTEEL     0
TECHM         0
TITAN         0
UPL           0
ULTRACEMCO    0
WIPRO         0
dtype: int64

In [43]:
stonks=allData.columns.to_list()

In [44]:
Date = pd.read_csv('nifty50_stocks/'+stonks[8]+'.csv', usecols=["Date"]) #get dates from any stock csv file  
allData = pd.concat([allData,Date],axis = 1)#concatenate dates to the current dataframe
allData.set_index('Date',inplace = True) #set dates as index in the current dataframe

In [45]:
allData

,ADANIPORTS,ASIANPAINT,AXISBANK,BAJAJ-AUTO,BAJFINANCE,BAJAJFINSV,BPCL,BHARTIARTL,BRITANNIA,CIPLA,...,SBIN,SUNPHARMA,TCS,TATAMOTORS,TATASTEEL,TECHM,TITAN,UPL,ULTRACEMCO,WIPRO
Date,,,,,,,,,,,,,,,,,,,,,
2016-01-01,261.112030,850.608887,440.847687,2209.871338,602.348328,1978.543457,217.338654,302.993469,1374.428223,642.229675,...,222.831543,787.287170,1082.013306,401.737305,219.908173,461.389832,340.842285,279.519226,2785.781250,202.975677
2016-01-04,251.743073,852.593201,429.579071,2179.461182,598.059875,1954.307739,216.222977,290.802551,1368.077148,632.723877,...,215.886398,771.407227,1061.057739,376.897339,219.481003,458.151581,340.212952,275.393219,2711.943848,203.431641
2016-01-05,249.547195,871.807617,427.668335,2196.136230,592.664673,1940.843384,218.939453,287.821564,1365.361816,628.019958,...,213.000748,772.758789,1051.810791,374.298431,234.346603,463.031219,336.630768,276.313599,2696.061768,203.139801
2016-01-06,245.741058,858.013977,422.034027,2181.347900,603.474854,1933.413330,221.280106,286.709259,1381.469727,639.044739,...,212.120361,764.505066,1066.431152,365.751862,229.604980,465.870178,336.776001,281.423492,2698.281494,202.483200
2016-01-07,239.104660,844.413879,401.015594,2123.205322,603.380981,1921.943726,214.476547,286.842743,1356.088257,624.688110,...,204.979584,756.637512,1061.796509,343.410919,213.500595,453.183197,333.096954,264.951294,2631.596191,200.568176
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-04-26,730.750000,2557.899902,700.450012,3738.850098,4736.549805,10001.750000,418.899994,527.549988,3526.107910,905.400024,...,344.299988,634.700012,3085.706299,295.399994,940.750000,962.200012,1479.849976,590.650024,6275.899902,480.299988
2021-04-27,749.150024,2574.350098,699.549988,3785.500000,4865.049805,10091.349609,420.350006,534.299988,3528.100342,912.400024,...,353.049988,639.250000,3116.754150,301.500000,977.750000,969.250000,1495.099976,597.450012,6326.799805,485.049988
2021-04-28,746.250000,2614.550049,708.150024,3889.750000,5280.899902,10489.299805,417.500000,544.299988,3465.881348,910.200012,...,363.399994,643.400024,3108.892822,305.899994,971.400024,977.400024,1508.849976,608.049988,6360.799805,489.299988
2021-04-29,746.750000,2613.449951,719.400024,3836.449951,5484.850098,11176.549805,419.549988,540.849976,3456.067871,906.500000,...,359.399994,644.500000,3100.085693,301.899994,1031.349976,976.900024,1506.800049,615.799988,6382.450195,489.850006
2021-04-30,730.049988,2536.399902,714.900024,3833.750000,5451.899902,11041.650391,421.799988,536.750000,3436.241455,910.349976,...,353.500000,654.450012,3020.873291,293.850006,1034.000000,960.400024,1491.650024,606.900024,6278.950195,492.750000

In [47]:
allData.to_csv('nifty50_stock_data.csv')       #save the preprocessed dataframe in .csv format



> Sheet provides the codes for shorlisting the nifty50 stocks. Finally, the shortlisted stocks will be the sample unit for portfolio optimisation.

In [55]:
df=pd.read_csv('nifty50_stock_data.csv',parse_dates=['Date'],index_col='Date')
x =pd.read_csv('nifty50_stock_data.csv',parse_dates=['Date'],index_col='Date')
x = x.loc["2016-01-01" : "2020-12-31"]
#integrate the preprocessing codes. (finished)

In [61]:
def number_of_years(y):        #calculates the number of years of the dataset
  p=y.index[0]                 #date of first row in the dataset (datetime format)
  q=y.index[len(y)-1]          #date of last row in the dataset  (datetime format)
  return ((q-p).days+1)/365    #the difference give the number of total days (not trading days) over the total number of years in the dataset

In [62]:
trading_days=len(x)/number_of_years(x)                       #Trading days per year (automated)
x.reset_index(drop=True, inplace=True)

In [63]:
returns=x.pct_change()                                       #getting the returns as percentage change
returns.fillna(0,inplace=True)

In [64]:
mean_return=returns.mean()*trading_days                      #getting the annual mean returns of all the remaining stocks in nifty50

In [65]:
nifty = pd.read_csv('nifty50_index.csv',usecols=['Adj Close','Date'],parse_dates=['Date'],index_col='Date')
nifty = nifty.loc["2016-01-01" : "2020-12-31"]
nifty.reset_index(drop=True, inplace=True)                   #getting the nifty50 index close price
                                                             #adj. close price is ideal way. change it for the stocks too. (finished)

In [66]:
nifty['Adj Close'].fillna(method='bfill',axis=0,inplace=True)
nifty['Adj Close'].fillna(method='ffill',axis=0,inplace=True)

In [78]:
nifty_return = nifty.pct_change() 
nifty_return.fillna(0,inplace=True)
mean_nifty_return=nifty_return.mean()[0]*trading_days        #getting the annual mean returns of nifty50 index

In [68]:
def rempos(x):                                               #mark positive values as 0 because semideviation only has negative returns
  for i in range(0,len(x)):
    if x['Adj Close'][i]>0:
      x['Adj Close'][i]=0
  return x
def rempo(x):
  for i in range(0,len(x)):
    if x[i]>0:
      x[i]=0
  return x

In [69]:
drisk_nifty=rempos(nifty_return.copy()).std()[0]*trading_days   #downside risk i.e., semi-deviation of nifty50 index

In [70]:
risk_free_rate = 0.0346                   #initializing risk free rate that will be used in calculating both the ratios (absolute value)
#referred from url: https://www.rbi.org.in/Scripts/BS_NSDPDisplay.aspx?param=4&Id=24292
#In the above url, the 364 (1 year => 01-01-2021) day treasury bill is 3.46% , when taken absolute value => 0.0346
# (improved)

In [71]:
def ratio(a,b,c):                         #function to calculate ratio i.e. "(returns-(risk_free_rate))/deviation"
  return (a-c)/b                          #a => annual return, c => risk_free_rate, b => deviation (standard for sharpe, semi for sortino)

In [72]:
sort_nifty=ratio(mean_nifty_return,drisk_nifty,risk_free_rate)      #getting the sortino ratio of nifty50 index

In [73]:
for i in returns.columns.to_list():                                 #for every remaining stock in the data
  ret=returns[i].mean()*trading_days                                #get the annual mean return
  drisk=rempo(returns[i].copy()).std()*trading_days                 #get the semideviation
  sortino=ratio(ret,drisk,risk_free_rate)                           #get the sortiono ratio
  if sortino < sort_nifty:                                          #compare it with nifty50 index's sortino ratio
    returns.drop(labels=[i],axis=1,inplace=True)                    #if less, drop it
    x.drop(labels=[i],axis=1,inplace=True)
    df.drop(labels=[i],axis=1,inplace=True)                         #literature servey needed.

In [74]:
x                  
#high sortino

,ASIANPAINT,BAJFINANCE,BAJAJFINSV,BRITANNIA,DIVISLAB,HCLTECH,HDFCBANK,HINDALCO,HINDUNILVR,HDFC,...,JSWSTEEL,KOTAKBANK,NESTLEIND,RELIANCE,SHREECEM,TCS,TATASTEEL,TECHM,TITAN,WIPRO
0,850.608887,602.348328,1978.543457,1374.428223,1108.503052,385.106506,528.506653,82.550529,792.340698,1169.114624,...,93.927940,725.564270,5311.719238,486.556549,11121.029297,1082.013306,219.908173,461.389832,340.842285,202.975677
1,852.593201,598.059875,1954.307739,1368.077148,1096.297607,385.152100,519.647644,78.515373,794.607056,1130.328369,...,95.546753,703.665161,5205.810547,476.948639,10804.255859,1061.057739,219.481003,458.151581,340.212952,203.431641
2,871.807617,592.664673,1940.843384,1365.361816,1094.199951,383.717926,515.715759,80.314178,784.385376,1123.546631,...,99.058762,706.109497,5199.016113,481.668732,10867.756836,1051.810791,234.346603,463.031219,336.630768,203.139801
3,858.013977,603.474854,1933.413330,1381.469727,1084.378296,383.080475,517.997192,78.320908,779.852783,1123.453613,...,96.781441,701.969116,5251.443359,494.631134,11188.242188,1066.431152,229.604980,465.870178,336.776001,202.483200
4,844.413879,603.380981,1921.943726,1356.088257,1074.604370,375.636505,512.706055,74.528839,758.761841,1095.722656,...,93.868484,690.046875,5177.484863,485.550232,10725.758789,1061.796509,213.500595,453.183197,333.096954,200.568176
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1229,2648.250000,5184.899902,8992.549805,3546.181152,3749.600098,905.757813,1397.099976,236.949997,2402.250000,2455.149902,...,366.250000,1960.599976,18465.892578,1994.150024,23826.750000,2889.689209,622.299988,947.250000,1495.900024,381.342682
1230,2683.899902,5204.100098,8995.049805,3531.773926,3766.000000,908.171631,1412.849976,239.899994,2388.899902,2476.449951,...,386.600006,1988.900024,18496.724609,2003.300049,23715.550781,2909.603516,632.650024,947.099976,1543.550049,382.041077
1231,2696.800049,5200.500000,8976.049805,3521.728271,3784.199951,922.063171,1427.199951,235.600006,2384.300049,2518.949951,...,381.799988,1999.300049,18163.837891,1990.050049,23839.650391,2910.696045,632.200012,965.650024,1540.099976,384.136383
1232,2734.399902,5334.149902,8961.700195,3512.515381,3799.699951,926.792175,1432.500000,237.399994,2406.600098,2518.050049,...,386.100006,2017.949951,18279.806641,1995.500000,24599.949219,2889.639404,640.450012,983.250000,1552.599976,383.537720
1233,2764.500000,5295.200195,8906.349609,3505.115967,3841.899902,932.161682,1436.300049,240.550003,2395.399902,2558.649902,...,387.200012,1995.599976,18290.746094,1985.300049,24013.199219,2843.404053,643.650024,973.200012,1567.150024,385.383575

In [75]:
df

,ASIANPAINT,BAJFINANCE,BAJAJFINSV,BRITANNIA,DIVISLAB,HCLTECH,HDFCBANK,HINDALCO,HINDUNILVR,HDFC,...,JSWSTEEL,KOTAKBANK,NESTLEIND,RELIANCE,SHREECEM,TCS,TATASTEEL,TECHM,TITAN,WIPRO
Date,,,,,,,,,,,,,,,,,,,,,
2016-01-01,850.608887,602.348328,1978.543457,1374.428223,1108.503052,385.106506,528.506653,82.550529,792.340698,1169.114624,...,93.927940,725.564270,5311.719238,486.556549,11121.029297,1082.013306,219.908173,461.389832,340.842285,202.975677
2016-01-04,852.593201,598.059875,1954.307739,1368.077148,1096.297607,385.152100,519.647644,78.515373,794.607056,1130.328369,...,95.546753,703.665161,5205.810547,476.948639,10804.255859,1061.057739,219.481003,458.151581,340.212952,203.431641
2016-01-05,871.807617,592.664673,1940.843384,1365.361816,1094.199951,383.717926,515.715759,80.314178,784.385376,1123.546631,...,99.058762,706.109497,5199.016113,481.668732,10867.756836,1051.810791,234.346603,463.031219,336.630768,203.139801
2016-01-06,858.013977,603.474854,1933.413330,1381.469727,1084.378296,383.080475,517.997192,78.320908,779.852783,1123.453613,...,96.781441,701.969116,5251.443359,494.631134,11188.242188,1066.431152,229.604980,465.870178,336.776001,202.483200
2016-01-07,844.413879,603.380981,1921.943726,1356.088257,1074.604370,375.636505,512.706055,74.528839,758.761841,1095.722656,...,93.868484,690.046875,5177.484863,485.550232,10725.758789,1061.796509,213.500595,453.183197,333.096954,200.568176
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-04-26,2557.899902,4736.549805,10001.750000,3526.107910,3784.350098,918.745850,1404.800049,348.350006,2360.649902,2509.800049,...,655.799988,1759.650024,16779.318359,1937.849976,28062.599609,3085.706299,940.750000,962.200012,1479.849976,480.299988
2021-04-27,2574.350098,4865.049805,10091.349609,3528.100342,3908.949951,918.795288,1438.699951,366.250000,2379.850098,2518.399902,...,665.900024,1750.300049,16688.214844,1988.650024,28098.550781,3116.754150,977.750000,969.250000,1495.099976,485.049988
2021-04-28,2614.550049,5280.899902,10489.299805,3465.881348,3882.600098,913.799988,1476.800049,362.600006,2406.550049,2577.000000,...,662.650024,1811.449951,16543.800781,1997.300049,28687.550781,3108.892822,971.400024,977.400024,1508.849976,489.299988
2021-04-29,2613.449951,5484.850098,11176.549805,3456.067871,3910.850098,909.549988,1472.500000,372.149994,2407.600098,2538.850098,...,726.500000,1805.000000,16502.550781,2024.050049,28444.349609,3100.085693,1031.349976,976.900024,1506.800049,489.850006
2021-04-30,2536.399902,5451.899902,11041.650391,3436.241455,4062.350098,898.950012,1412.300049,364.399994,2353.750000,2420.100098,...,717.849976,1748.800049,16309.250000,1994.500000,27910.500000,3020.873291,1034.000000,960.400024,1491.650024,492.750000

In [76]:
df.to_csv('n50.csv')