In [1]:
import pandas as pd
import numpy as np
from datetime import date

In [2]:
from yahoofinance import HistoricalPrices as get_history #ensure yahoofinance package is installed

# Code for Data Collection
*Please execute this in jupyter notebook to get the data quickly*

In [3]:
start_date = date(2016,1,1) #date in Year, Month, Day
end_date = date(2021,5,1)

In [4]:
nifty_500_stocks_list=pd.read_csv('ind_nifty500list.csv') #use the csv file from nifty website
nifty_500_stocks = list(nifty_500_stocks_list['Symbol']) #Choose the stock symbols

In [5]:
k=0
for i in nifty_500_stocks :
    print(str(k+1)+"getting: ", i)
    k+=1
    x = get_history(instrument= i+'.NS',start_date=start_date,end_date=end_date) #yahoofinance function to get the stock data
    x.to_csv('nifty500_stocks/{}.csv'.format(i))

1getting:  3MINDIA
2getting:  ABB
3getting:  POWERINDIA
4getting:  ACC
5getting:  AIAENG
6getting:  APLAPOLLO
7getting:  AUBANK
8getting:  AARTIDRUGS
9getting:  AARTIIND
10getting:  AAVAS
11getting:  ABBOTINDIA
12getting:  ADANIENT
13getting:  ADANIGREEN
14getting:  ADANIPORTS
15getting:  ATGL
16getting:  ADANITRANS
17getting:  ABCAPITAL
18getting:  ABFRL
19getting:  ADVENZYMES
20getting:  AEGISCHEM
21getting:  AFFLE
22getting:  AJANTPHARM
23getting:  AKZOINDIA
24getting:  ALEMBICLTD
25getting:  APLLTD
26getting:  ALKEM
27getting:  ALKYLAMINE
28getting:  ALOKINDS
29getting:  AMARAJABAT
30getting:  AMBER
31getting:  AMBUJACEM
32getting:  APOLLOHOSP
33getting:  APOLLOTYRE
34getting:  ASHOKLEY
35getting:  ASHOKA
36getting:  ASIANPAINT
37getting:  ASTERDM
38getting:  ASTRAZEN
39getting:  ASTRAL
40getting:  ATUL
41getting:  AUROPHARMA
42getting:  AVANTIFEED
43getting:  DMART
44getting:  AXISBANK
45getting:  BASF
46getting:  BEML
47getting:  BSE
48getting:  BAJAJ-AUTO
49getting:  BAJAJCON
50getting:  BAJAJELEC
51getting:  BAJFINANCE
52getting:  BAJAJFINSV
53getting:  BAJAJHLDNG
54getting:  BALKRISIND
55getting:  BALMLAWRIE
56getting:  BALRAMCHIN
57getting:  BANDHANBNK
58getting:  BANKBARODA
59getting:  BANKINDIA
60getting:  MAHABANK
61getting:  BATAINDIA
62getting:  BAYERCROP
63getting:  BERGEPAINT
64getting:  BDL
65getting:  BEL
66getting:  BHARATFORG
67getting:  BHEL
68getting:  BPCL
69getting:  BHARATRAS
70getting:  BHARTIARTL
71getting:  BIOCON
72getting:  BIRLACORPN
73getting:  BSOFT
74getting:  BLISSGVS
75getting:  BLUEDART
76getting:  BLUESTARCO
77getting:  BBTC
78getting:  BOMDYEING
79getting:  BOSCHLTD
80getting:  BRIGADE
81getting:  BRITANNIA
82getting:  CARERATING
83getting:  CCL
84getting:  CESC
85getting:  CRISIL
86getting:  CSBBANK
87getting:  CADILAHC
88getting:  CANFINHOME
89getting:  CANBK
90getting:  CAPLIPOINT
91getting:  CGCL
92getting:  CARBORUNIV
93getting:  CASTROLIND
94getting:  CEATLTD
95getting:  CENTRALBK
96getting:  CDSL
97getting:  CENTURYPLY
98getting:  CENTURYTEX
99getting:  CERA
100getting:  CHALET
101getting:  CHAMBLFERT
102getting:  CHENNPETRO
103getting:  CHOLAHLDNG
104getting:  CHOLAFIN
105getting:  CIPLA
106getting:  CUB
107getting:  COALINDIA
108getting:  COCHINSHIP
109getting:  COFORGE
110getting:  COLPAL
111getting:  CONCOR
112getting:  COROMANDEL
113getting:  CREDITACC
114getting:  CROMPTON
115getting:  CUMMINSIND
116getting:  CYIENT
117getting:  DBCORP
118getting:  DCBBANK
119getting:  DCMSHRIRAM
120getting:  DLF
121getting:  DABUR
122getting:  DALBHARAT
123getting:  DEEPAKNTR
124getting:  DELTACORP
125getting:  DHANI
126getting:  DHANUKA
127getting:  DBL
128getting:  DISHTV
129getting:  DCAL
130getting:  DIVISLAB
131getting:  DIXON
132getting:  LALPATHLAB
133getting:  DRREDDY
134getting:  EIDPARRY
135getting:  EIHOTEL
136getting:  EPL
137getting:  ESABINDIA
138getting:  EDELWEISS
139getting:  EICHERMOT
140getting:  ELGIEQUIP
141getting:  EMAMILTD
142getting:  ENDURANCE
143getting:  ENGINERSIN
144getting:  EQUITAS
145getting:  ERIS
146getting:  ESCORTS
147getting:  EXIDEIND
148getting:  FDC
149getting:  FEDERALBNK
150getting:  FINEORG
151getting:  FINCABLES
152getting:  FINPIPE
153getting:  FSL
154getting:  FORTIS
155getting:  FCONSUMER
156getting:  FRETAIL
157getting:  GAIL
158getting:  GEPIL
159getting:  GHCL
160getting:  GMMPFAUDLR
161getting:  GMRINFRA
162getting:  GALAXYSURF
163getting:  GRSE
164getting:  GARFIBRES
165getting:  GICRE
166getting:  GILLETTE
167getting:  GLAXO
168getting:  GLENMARK
169getting:  GODFRYPHLP
170getting:  GODREJAGRO
171getting:  GODREJCP
172getting:  GODREJIND
173getting:  GODREJPROP
174getting:  GRANULES
175getting:  GRAPHITE
176getting:  GRASIM
177getting:  GESHIP
178getting:  GREAVESCOT
179getting:  GRINDWELL
180getting:  GUJALKALI
181getting:  GAEL
182getting:  FLUOROCHEM
183getting:  GUJGASLTD
184getting:  GMDCLTD
185getting:  GNFC
186getting:  GPPL
187getting:  GSFC
188getting:  GSPL
189getting:  GULFOILLUB
190getting:  HEG
191getting:  HCLTECH
192getting:  HDFCAMC
193getting:  HDFCBANK
194getting:  HDFCLIFE
195getting:  HFCL
196getting:  HATHWAY
197getting:  HATSUN
198getting:  HAVELLS
199getting:  HEIDELBERG
200getting:  HERITGFOOD
201getting:  HEROMOTOCO
202getting:  HSCL
203getting:  HINDALCO
204getting:  HAL
205getting:  HINDCOPPER
206getting:  HINDPETRO
207getting:  HINDUNILVR
208getting:  HINDZINC
209getting:  HONAUT
210getting:  HUDCO
211getting:  HDFC
212getting:  HUHTAMAKI
213getting:  ICICIBANK
214getting:  ICICIGI
215getting:  ICICIPRULI
216getting:  ISEC
217getting:  ICRA
218getting:  IDBI
219getting:  IDFCFIRSTB
220getting:  IDFC
221getting:  IFBIND
222getting:  IIFL
223getting:  IIFLWAM
224getting:  IOLCP
225getting:  IRB
226getting:  IRCON
227getting:  ITC
228getting:  ITI
229getting:  INDIACEM
230getting:  IBULHSGFIN
231getting:  IBREALEST
232getting:  INDIAMART
233getting:  INDIANB
234getting:  IEX
235getting:  INDHOTEL
236getting:  IOC
237getting:  IOB
238getting:  IRCTC
239getting:  INDOCO
240getting:  IGL
241getting:  INDUSTOWER
242getting:  INDUSINDBK
243getting:  NAUKRI
244getting:  INFY
245getting:  INGERRAND
246getting:  INOXLEISUR
247getting:  INDIGO
248getting:  IPCALAB
249getting:  JBCHEPHARM
250getting:  JKCEMENT
251getting:  JKLAKSHMI
252getting:  JKPAPER
253getting:  JKTYRE
254getting:  JMFINANCIL
255getting:  JSWENERGY
256getting:  JSWSTEEL
257getting:  JTEKTINDIA
258getting:  JAGRAN
259getting:  JAICORPLTD
260getting:  J&KBANK
261getting:  JAMNAAUTO
262getting:  JINDALSAW
263getting:  JSLHISAR
264getting:  JSL
265getting:  JINDALSTEL
266getting:  JCHAC
267getting:  JUBLFOOD
268getting:  JUSTDIAL
269getting:  JYOTHYLAB
270getting:  KEI
271getting:  KNRCON
272getting:  KRBL
273getting:  KSB
274getting:  KAJARIACER
275getting:  KALPATPOWR
276getting:  KANSAINER
277getting:  KTKBANK
278getting:  KARURVYSYA
279getting:  KSCL
280getting:  KEC
281getting:  KOLTEPATIL
282getting:  KOTAKBANK
283getting:  L&TFH
284getting:  LTTS
285getting:  LICHSGFIN
286getting:  LAOPALA
287getting:  LAXMIMACH
288getting:  LTI
289getting:  LT
290getting:  LAURUSLABS
291getting:  LEMONTREE
292getting:  LINDEINDIA
293getting:  LUPIN
294getting:  LUXIND
295getting:  MASFIN
296getting:  MMTC
297getting:  MOIL
298getting:  MRF
299getting:  MGL
300getting:  MAHSCOOTER
301getting:  MAHSEAMLES
302getting:  M&MFIN
303getting:  M&M
304getting:  MAHINDCIE
305getting:  MHRIL
306getting:  MAHLOG
307getting:  MANAPPURAM
308getting:  MRPL
309getting:  MARICO
310getting:  MARUTI
311getting:  MFSL
312getting:  METROPOLIS
313getting:  MINDTREE
314getting:  MINDACORP
315getting:  MINDAIND
316getting:  MIDHANI
317getting:  MOTHERSUMI
318getting:  MOTILALOFS
319getting:  MPHASIS
320getting:  MCX
321getting:  MUTHOOTFIN
322getting:  NATCOPHARM
323getting:  NBCC
324getting:  NCC
325getting:  NESCO
326getting:  NHPC
327getting:  NLCINDIA
328getting:  NMDC
329getting:  NOCIL
330getting:  NTPC
331getting:  NH
332getting:  NATIONALUM
333getting:  NFL
334getting:  NAVINFLUOR
335getting:  NAVNETEDUL
336getting:  NESTLEIND
337getting:  NETWORK18
338getting:  NILKAMAL
339getting:  NAM-INDIA
340getting:  OBEROIRLTY
341getting:  ONGC
342getting:  OIL
343getting:  OMAXE
344getting:  OFSS
345getting:  ORIENTCEM
346getting:  ORIENTELEC
347getting:  ORIENTREF
348getting:  PIIND
349getting:  PNBHOUSING
350getting:  PNCINFRA
351getting:  PSPPROJECT
352getting:  PTC
353getting:  PVR
354getting:  PAGEIND
355getting:  PERSISTENT
356getting:  PETRONET
357getting:  PFIZER
358getting:  PHILIPCARB
359getting:  PHOENIXLTD
360getting:  PIDILITIND
361getting:  PEL
362getting:  POLYMED
363getting:  POLYCAB
364getting:  POLYPLEX
365getting:  PFC
366getting:  POWERGRID
367getting:  PRAJIND
368getting:  PRESTIGE
369getting:  PRSMJOHNSN
370getting:  PGHL
371getting:  PGHH
372getting:  PNB
373getting:  QUESS
374getting:  RBLBANK
375getting:  RECLTD
376getting:  RITES
377getting:  RADICO
378getting:  RVNL
379getting:  RAIN
380getting:  RAJESHEXPO
381getting:  RALLIS
382getting:  RCF
383getting:  RATNAMANI
384getting:  RAYMOND
385getting:  REDINGTON
386getting:  RELAXO
387getting:  RELIANCE
388getting:  SBICARD
389getting:  SBILIFE
390getting:  SIS
391getting:  SJVN
392getting:  SKFINDIA
393getting:  SRF
394getting:  SANOFI

395getting:  SCHAEFFLER
396getting:  SCHNEIDER
397getting:  SEQUENT
398getting:  SFL
399getting:  SHILPAMED
400getting:  SCI
401getting:  SHOPERSTOP
402getting:  SHREECEM
403getting:  SHRIRAMCIT
404getting:  SRTRANSFIN
405getting:  SIEMENS
406getting:  SOBHA
407getting:  SOLARINDS
408getting:  SOLARA
409getting:  SONATSOFTW
410getting:  SOUTHBANK
411getting:  SPICEJET
412getting:  STARCEMENT
413getting:  SBIN
414getting:  SAIL
415getting:  SWSOLAR
416getting:  STLTECH
417getting:  STAR
418getting:  SUDARSCHEM
419getting:  SUMICHEM
420getting:  SPARC
421getting:  SUNPHARMA
422getting:  SUNTV
423getting:  SUNDARMFIN
424getting:  SUNDRMFAST
425getting:  SUNTECK
426getting:  SUPRAJIT
427getting:  SUPREMEIND
428getting:  SUPPETRO
429getting:  SUVENPHAR
430getting:  SUZLON
431getting:  SWANENERGY
432getting:  SWARAJENG
433getting:  SYMPHONY
434getting:  SYNGENE
435getting:  TCIEXP
436getting:  TCNSBRANDS
437getting:  TTKPRESTIG
438getting:  TVTODAY
439getting:  TV18BRDCST
440getting:  TVSMOTOR
441getting:  TASTYBITE
442getting:  TATACHEM
443getting:  TATACOFFEE
444getting:  TATACOMM
445getting:  TCS
446getting:  TATACONSUM
447getting:  TATAELXSI
448getting:  TATAINVEST
449getting:  TATAMTRDVR
450getting:  TATAMOTORS
451getting:  TATAPOWER
452getting:  TATASTLBSL
453getting:  TATASTEEL
454getting:  TEAMLEASE
455getting:  TECHM
456getting:  NIACL
457getting:  RAMCOCEM
458getting:  THERMAX
459getting:  THYROCARE
460getting:  TIMKEN
461getting:  TITAN
462getting:  TORNTPHARM
463getting:  TORNTPOWER
464getting:  TRENT
465getting:  TRIDENT
466getting:  TIINDIA
467getting:  UCOBANK
468getting:  UFLEX
469getting:  UPL
470getting:  UJJIVAN
471getting:  UJJIVANSFB
472getting:  ULTRACEMCO
473getting:  UNIONBANK
474getting:  UBL
475getting:  MCDOWELL-N
476getting:  VGUARD
477getting:  VMART
478getting:  VIPIND
479getting:  VRLLOG
480getting:  VSTIND
481getting:  VAIBHAVGBL
482getting:  VAKRANGEE
483getting:  VTL
484getting:  VARROC
485getting:  VBL
486getting:  VENKEYS
487getting:  VINATIORGA
488getting:  IDEA
489getting:  VOLTAS
490getting:  WABCOINDIA
491getting:  WELCORP
492getting:  WELSPUNIND
493getting:  WESTLIFE
494getting:  WHIRLPOOL
495getting:  WIPRO
496getting:  WOCKPHARMA
497getting:  YESBANK
498getting:  ZEEL
499getting:  ZENSARTECH
500getting:  ZYDUSWELL
501getting:  ECLERX

# Code for preprocessing the data

In [6]:
nifty_500_stocks_list=pd.read_csv('ind_nifty500list.csv') #use the csv file from nifty website
nifty_500_stocks = list(nifty_500_stocks_list['Symbol']) #Choose the stock symbols

In [26]:
allData = pd.DataFrame()                                #creating an empty dataframe

In [27]:
 for i in nifty_500_stocks:
    x = pd.read_csv('nifty500_stocks/{}.csv'.format(i), usecols=["Adj Close"])
    allData = pd.concat([allData,x],axis = 1)            
                                                         #getting each stock data one by one and concatanating it into the 'allData' frame

In [28]:
allData.columns=nifty_500_stocks                                      #setting up the column names of the dataframe

In [29]:
allData.to_csv('raw_data.csv')  #saving the data without preprocessing

In [30]:
allData

,3MINDIA,ABB,POWERINDIA,ACC,AIAENG,APLAPOLLO,AUBANK,AARTIDRUGS,AARTIIND,AAVAS,...,WELSPUNIND,WESTLIFE,WHIRLPOOL,WIPRO,WOCKPHARMA,YESBANK,ZEEL,ZENSARTECH,ZYDUSWELL,ECLERX
0,11321.950195,1066.930664,712.334473,1247.206421,867.168823,144.383698,566.169250,144.525604,248.652145,774.349976,...,85.008072,282.049988,638.013733,202.975861,1582.111328,138.945892,419.460876,193.031921,830.219421,1416.220337
1,10935.799805,1070.466553,747.951172,1220.285522,847.834595,145.164093,628.350586,142.959702,246.615967,767.700012,...,82.339165,289.750000,640.025696,203.432037,1557.103394,133.880875,408.850830,189.327927,825.170898,1387.886963
2,10784.349609,1046.001953,785.313843,1217.834229,838.550293,152.120255,689.833252,143.263153,247.941849,791.299988,...,82.017227,285.250000,648.319153,203.140244,1558.385864,134.250809,411.854523,189.336807,831.517761,1378.970825
3,10644.599609,1029.803711,788.157166,1198.812622,825.293945,150.328232,597.659180,142.607681,244.485062,758.299988,...,79.595627,277.950012,661.716553,202.483627,1555.327637,133.520462,410.013519,189.168030,830.652161,1379.366943
4,10673.750000,1006.724976,788.805725,1180.789917,802.753357,144.846161,594.964294,136.611053,241.927979,781.400024,...,79.642288,281.049988,652.932251,200.568375,1524.943359,128.777939,402.504120,181.165024,817.910583,1397.744019
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1309,26181.150391,1369.099976,NaN,1844.750000,1900.400024,1287.650024,NaN,715.599976,1492.050049,NaN,...,79.229347,NaN,2174.949951,480.299988,516.900024,14.050000,186.399994,268.649994,2162.699951,1171.250000
1310,25505.300781,1384.349976,NaN,1859.750000,1905.650024,1313.099976,NaN,723.150024,1562.900024,NaN,...,79.628738,NaN,2161.050049,485.049988,513.650024,14.750000,188.149994,266.549988,2102.800049,1165.650024
1311,25674.300781,1387.900024,NaN,1872.150024,1920.150024,1321.150024,NaN,719.299988,1539.199951,NaN,...,82.224785,NaN,2145.750000,489.299988,510.750000,14.800000,189.100006,269.549988,2123.899902,1177.800049
1312,25494.349609,1381.300049,NaN,1877.050049,1880.150024,1330.150024,NaN,718.750000,1556.949951,NaN,...,81.825394,NaN,2171.500000,489.850006,512.549988,14.500000,186.550003,268.250000,2096.199951,1230.599976
1313,25537.949219,1381.250000,NaN,1882.750000,1862.750000,1302.250000,NaN,709.950012,1604.849976,NaN,...,79.379120,NaN,2221.449951,492.750000,514.650024,14.550000,185.600006,264.299988,2097.899902,1245.849976

In [31]:
allData.isnull().sum()                             #getting the number of null values in each column as a list

3MINDIA          2
ABB              2
POWERINDIA    1045
ACC              2
AIAENG           2
              ...
YESBANK          2
ZEEL             2
ZENSARTECH       2
ZYDUSWELL        2
ECLERX           2
Length: 501, dtype: int64

In [32]:
for i in allData.isnull().sum():
    if i > 2 and i < 28:
        print(i)

20
5

In [33]:
                                                                   #filling the null values with forward fill and backward fill methods
for i in allData.columns.to_list():
    if allData[i].isnull().sum()>26:                               # if more than 2% of data is missing, drop the column
        allData.drop(i,axis=1,inplace=True)
    else:
        allData[i].fillna(method='bfill',axis=0,inplace=True)
        allData[i].fillna(method='ffill',axis=0,inplace=True)               #(important)
        
# 2% of 1314(total trading days from 01-01-2016 till 01-05-2021) is nearly 26 days which is greater than trading days in a month.

In [34]:
allData.isnull().sum()                                       #getting total null values in dataframe

3MINDIA       0
ABB           0
ACC           0
AIAENG        0
APLAPOLLO     0
             ..
YESBANK       0
ZEEL          0
ZENSARTECH    0
ZYDUSWELL     0
ECLERX        0
Length: 414, dtype: int64

In [35]:
stonks=allData.columns.to_list()

In [36]:
Date = pd.read_csv('nifty500_stocks/'+stonks[1]+'.csv', usecols=["Date"]) #get dates from any stock csv file  
allData = pd.concat([allData,Date],axis = 1)#concatenate dates to the current dataframe
allData.set_index('Date',inplace = True) #set dates as index in the current dataframe

In [37]:
allData

,3MINDIA,ABB,ACC,AIAENG,APLAPOLLO,AARTIDRUGS,AARTIIND,ABBOTINDIA,ADANIENT,ADANIPORTS,...,WELCORP,WELSPUNIND,WHIRLPOOL,WIPRO,WOCKPHARMA,YESBANK,ZEEL,ZENSARTECH,ZYDUSWELL,ECLERX
Date,,,,,,,,,,,,,,,,,,,,,
2016-01-01,11321.950195,1066.930664,1247.206421,867.168823,144.383698,144.525604,248.652145,5673.990234,47.666069,261.112030,...,105.272064,85.008072,638.013733,202.975861,1582.111328,138.945892,419.460876,193.031921,830.219421,1416.220337
2016-01-04,10935.799805,1070.466553,1220.285522,847.834595,145.164093,142.959702,246.615967,5707.625000,45.020885,251.743073,...,102.066521,82.339165,640.025696,203.432037,1557.103394,133.880875,408.850830,189.327927,825.170898,1387.886963
2016-01-05,10784.349609,1046.001953,1217.834229,838.550293,152.120255,143.263153,247.941849,5656.812012,46.872513,249.547195,...,105.179153,82.017227,648.319153,203.140244,1558.385864,134.250809,411.854523,189.336807,831.517761,1378.970825
2016-01-06,10644.599609,1029.803711,1198.812622,825.293945,150.328232,142.607681,244.485062,5565.869629,45.629280,245.741058,...,103.785439,79.595627,661.716553,202.483627,1555.327637,133.520462,410.013519,189.168030,830.652161,1379.366943
2016-01-07,10673.750000,1006.724976,1180.789917,802.753357,144.846161,136.611053,241.927979,5443.218262,42.296364,239.104660,...,99.557838,79.642288,652.932251,200.568375,1524.943359,128.777939,402.504120,181.165024,817.910583,1397.744019
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-04-26,26181.150391,1369.099976,1844.750000,1900.400024,1287.650024,715.599976,1492.050049,15052.849609,1173.349976,730.750000,...,144.199997,79.229347,2174.949951,480.299988,516.900024,14.050000,186.399994,268.649994,2162.699951,1171.250000
2021-04-27,25505.300781,1384.349976,1859.750000,1905.650024,1313.099976,723.150024,1562.900024,15202.599609,1191.150024,749.150024,...,152.149994,79.628738,2161.050049,485.049988,513.650024,14.750000,188.149994,266.549988,2102.800049,1165.650024
2021-04-28,25674.300781,1387.900024,1872.150024,1920.150024,1321.150024,719.299988,1539.199951,15172.900391,1185.199951,746.250000,...,147.949997,82.224785,2145.750000,489.299988,510.750000,14.800000,189.100006,269.549988,2123.899902,1177.800049
2021-04-29,25494.349609,1381.300049,1877.050049,1880.150024,1330.150024,718.750000,1556.949951,14997.250000,1182.300049,746.750000,...,145.750000,81.825394,2171.500000,489.850006,512.549988,14.500000,186.550003,268.250000,2096.199951,1230.599976
2021-04-30,25537.949219,1381.250000,1882.750000,1862.750000,1302.250000,709.950012,1604.849976,15151.750000,1158.699951,730.049988,...,142.899994,79.379120,2221.449951,492.750000,514.650024,14.550000,185.600006,264.299988,2097.899902,1245.849976

In [38]:
allData.to_csv('nifty500_stock_data.csv')       #save the preprocessed dataframe in .csv format



> Sheet provides the codes for shorlisting the nifty500 stocks. Finally, the shortlisted stocks will be the sample unit for portfolio optimisation.

In [39]:
df=pd.read_csv('nifty500_stock_data.csv',parse_dates=['Date'],index_col='Date')
x =pd.read_csv('nifty500_stock_data.csv',parse_dates=['Date'],index_col='Date')
x = x.loc["2016-01-01" : "2020-12-31"]
#integrate the preprocessing codes. (finished)

In [40]:
def number_of_years(y):        #calculates the number of years of the dataset
  p=y.index[0]                 #date of first row in the dataset (datetime format)
  q=y.index[len(y)-1]          #date of last row in the dataset  (datetime format)
  return ((q-p).days+1)/365    #the difference give the number of total days (not trading days) over the total number of years in the dataset

In [41]:
trading_days=len(x)/number_of_years(x)                       #Trading days per year (automated)
x.reset_index(drop=True, inplace=True)

In [42]:
returns=x.pct_change()                                       #getting the returns as percentage change
returns.fillna(0,inplace=True)

In [43]:
mean_return=returns.mean()*trading_days                      #getting the annual mean returns of all the remaining stocks in nifty50

In [44]:
nifty = pd.read_csv('nifty500_index.csv',usecols=['Adj Close','Date'],parse_dates=['Date'],index_col='Date')
nifty = nifty.loc["2016-01-01" : "2020-12-31"]
nifty.reset_index(drop=True, inplace=True)                   #getting the nifty500 index adjusted close price 
                                                             # adj. close price is ideal way. change it for the stocks too. (important)
                                                             #Can't find the adj. closing price of all the stocks (found in yahoo finance)

In [45]:
nifty['Adj Close'].fillna(method='bfill',axis=0,inplace=True)
nifty['Adj Close'].fillna(method='ffill',axis=0,inplace=True)

In [46]:
nifty_return = nifty.pct_change() 
nifty_return.fillna(0,inplace=True)
mean_nifty_return=nifty_return.mean()[0]*trading_days        #getting the annual mean returns of nifty500 index

In [47]:
def rempos(x):                                               #mark positive values as 0 because semideviation only has negative returns
  for i in range(0,len(x)):
    if x['Adj Close'][i]>0:
      x['Adj Close'][i]=0
  return x
def rempo(x):
  for i in range(0,len(x)):
    if x[i]>0:
      x[i]=0
  return x

In [48]:
drisk_nifty=rempos(nifty_return.copy()).std()[0]*trading_days   #downside risk i.e., semi-deviation of nifty50 index

In [49]:
risk_free_rate = 0.0346                   #initializing risk free rate that will be used in calculating both the ratios (absolute value)
#referred from url: https://www.rbi.org.in/Scripts/BS_NSDPDisplay.aspx?param=4&Id=24292
#In the above url, the 364 (1 year => 01-01-2021) day treasury bill is 3.46% , when taken absolute value => 0.0346
# (improved)

In [50]:
def ratio(a,b,c):                         #function to calculate ratio i.e. "(returns-(risk_free_rate))/deviation"
  return (a-c)/b                          #a => annual return, c => risk_free_rate, b => deviation (standard for sharpe, semi for sortino)

In [51]:
sort_nifty=ratio(mean_nifty_return,drisk_nifty,risk_free_rate)      #getting the sortino ratio of nifty500 index

In [52]:
for i in returns.columns.to_list():                                 #for every remaining stock in the data
  ret=returns[i].mean()*trading_days                                #get the annual mean return
  drisk=rempo(returns[i].copy()).std()*trading_days                 #get the semideviation
  sortino=ratio(ret,drisk,risk_free_rate)                           #get the sortiono ratio
  if sortino < sort_nifty:                                          #compare it with nifty500 index's sortino ratio
    returns.drop(labels=[i],axis=1,inplace=True)                    #if less, drop it
    x.drop(labels=[i],axis=1,inplace=True)
    df.drop(labels=[i],axis=1,inplace=True)                         #literature servey needed.

In [53]:
x             
#high sortino

,3MINDIA,AIAENG,APLAPOLLO,AARTIDRUGS,AARTIIND,ABBOTINDIA,ADANIENT,ADANITRANS,AEGISCHEM,AKZOINDIA,...,VMART,VIPIND,VSTIND,VAIBHAVGBL,VENKEYS,VINATIORGA,VOLTAS,WHIRLPOOL,WIPRO,ZYDUSWELL
0,11321.950195,867.168823,144.383698,144.525604,248.652145,5673.990234,47.666069,41.049999,102.688416,1264.629517,...,614.104858,96.934898,1446.978149,459.678467,324.586823,224.686325,302.245453,638.013733,202.975861,830.219421
1,10935.799805,847.834595,145.164093,142.959702,246.615967,5707.625000,45.020885,38.650002,102.446335,1249.578613,...,581.427551,93.276970,1441.762329,449.980774,320.425507,222.553543,290.931915,640.025696,203.432037,825.170898
2,10784.349609,838.550293,152.120255,143.263153,247.941849,5656.812012,46.872513,38.799999,106.029037,1238.562622,...,576.304688,93.652122,1441.804810,451.901978,323.020233,220.133163,288.423126,648.319153,203.140244,831.517761
3,10644.599609,825.293945,150.328232,142.607681,244.485062,5565.869629,45.629280,38.349998,101.429634,1227.818604,...,562.875549,93.980408,1437.309814,449.843506,321.404633,217.736801,289.417175,661.716553,202.483627,830.652161
4,10673.750000,802.753357,144.846161,136.611053,241.927979,5443.218262,42.296364,37.150002,100.316071,1219.159790,...,539.001709,89.994217,1447.190186,444.400055,307.696564,213.015900,272.801941,652.932251,200.568375,817.910583
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1229,21153.199219,1996.400024,761.000000,705.450012,1205.300049,15727.400391,473.649994,428.100006,245.800003,2213.753662,...,2500.949951,350.450012,3767.449951,2192.730469,1671.750000,1154.300049,810.950012,2528.000000,381.342682,1947.599976
1230,21356.300781,2060.949951,808.799988,704.500000,1212.199951,15697.700195,490.850006,433.649994,256.000000,2306.053467,...,2548.500000,356.100006,3819.750000,444.210846,1671.099976,1147.599976,816.000000,2580.600098,382.041077,1927.900024
1231,21170.250000,2005.400024,819.650024,704.400024,1227.449951,15701.900391,489.200012,429.149994,248.649994,2290.050781,...,2498.100098,356.899994,3776.199951,450.114868,1694.750000,1219.000000,814.349976,2509.350098,384.136383,1981.849976
1232,20865.599609,1995.000000,835.349976,703.599976,1219.400024,15628.400391,484.149994,436.200012,250.199997,2379.625732,...,2464.350098,351.850006,3723.350098,482.706909,1738.250000,1219.699951,819.799988,2586.850098,383.537720,1966.199951
1233,20830.550781,1974.349976,883.000000,705.150024,1234.800049,15769.099609,479.549988,437.500000,252.000000,2377.594238,...,2542.449951,364.500000,3704.399902,488.062469,1746.650024,1208.199951,825.650024,2629.000000,385.383575,1990.500000

In [54]:
df

,3MINDIA,AIAENG,APLAPOLLO,AARTIDRUGS,AARTIIND,ABBOTINDIA,ADANIENT,ADANITRANS,AEGISCHEM,AKZOINDIA,...,VMART,VIPIND,VSTIND,VAIBHAVGBL,VENKEYS,VINATIORGA,VOLTAS,WHIRLPOOL,WIPRO,ZYDUSWELL
Date,,,,,,,,,,,,,,,,,,,,,
2016-01-01,11321.950195,867.168823,144.383698,144.525604,248.652145,5673.990234,47.666069,41.049999,102.688416,1264.629517,...,614.104858,96.934898,1446.978149,459.678467,324.586823,224.686325,302.245453,638.013733,202.975861,830.219421
2016-01-04,10935.799805,847.834595,145.164093,142.959702,246.615967,5707.625000,45.020885,38.650002,102.446335,1249.578613,...,581.427551,93.276970,1441.762329,449.980774,320.425507,222.553543,290.931915,640.025696,203.432037,825.170898
2016-01-05,10784.349609,838.550293,152.120255,143.263153,247.941849,5656.812012,46.872513,38.799999,106.029037,1238.562622,...,576.304688,93.652122,1441.804810,451.901978,323.020233,220.133163,288.423126,648.319153,203.140244,831.517761
2016-01-06,10644.599609,825.293945,150.328232,142.607681,244.485062,5565.869629,45.629280,38.349998,101.429634,1227.818604,...,562.875549,93.980408,1437.309814,449.843506,321.404633,217.736801,289.417175,661.716553,202.483627,830.652161
2016-01-07,10673.750000,802.753357,144.846161,136.611053,241.927979,5443.218262,42.296364,37.150002,100.316071,1219.159790,...,539.001709,89.994217,1447.190186,444.400055,307.696564,213.015900,272.801941,652.932251,200.568375,817.910583
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-04-26,26181.150391,1900.400024,1287.650024,715.599976,1492.050049,15052.849609,1173.349976,1055.199951,286.000000,2214.350098,...,2616.800049,335.000000,3318.649902,821.739990,1525.900024,1666.349976,946.150024,2174.949951,480.299988,2162.699951
2021-04-27,25505.300781,1905.650024,1313.099976,723.150024,1562.900024,15202.599609,1191.150024,1044.099976,290.799988,2229.100098,...,2630.399902,333.000000,3309.199951,830.440002,1526.300049,1725.750000,976.400024,2161.050049,485.049988,2102.800049
2021-04-28,25674.300781,1920.150024,1321.150024,719.299988,1539.199951,15172.900391,1185.199951,1056.550049,313.350006,2240.600098,...,2645.699951,347.549988,3289.500000,860.880005,1552.050049,1720.199951,962.150024,2145.750000,489.299988,2123.899902
2021-04-29,25494.349609,1880.150024,1330.150024,718.750000,1556.949951,14997.250000,1182.300049,1050.150024,308.549988,2224.949951,...,2704.199951,357.649994,3201.300049,851.000000,1572.949951,1689.349976,967.099976,2171.500000,489.850006,2096.199951
2021-04-30,25537.949219,1862.750000,1302.250000,709.950012,1604.849976,15151.750000,1158.699951,1049.900024,304.200012,2243.149902,...,2652.600098,345.399994,3229.100098,833.960022,1556.550049,1697.699951,957.150024,2221.449951,492.750000,2097.899902

In [56]:
df.to_csv('np5k.csv')